### ISSUE TITLE
Renew license

### ISSUE THREAD

**Issue by ozcan-durak** [sinanejadebrahim/jira-crack#2]
Hi what do you suggest after 5 month of expiration, do we need to reinstall ?

**Comment by ozcan-durak** [comment]
Currently it show 37 days left to renew ? do you have any suggestion ?

**Comment by sinanejadebrahim** [comment]
hi,
you can export / import your data after reinstalling and use the code again but if it didn't work you can use this repo [atlassian-agent](https://gitee.com/pengzhile/atlassian-agent) and generate a new license code, jira will be activated until 2089 (:
I haven't had time but I'll update my repo soon.for now you can just use this link that I gave you.

**Comment by ozcan-durak** [comment]
I have tried the repo you gave above but with google translate i m not sure if i have done correct.

please let me know once you try out :) 

Regards

**Comment by sinanejadebrahim** [comment]
i haven't used it my self, but people have used it and it worked, you only need to run the agent on that repo to get a new license code. after that you can just use my repo and at the end use the new code you generated to activate jira.

**Comment by dinhquy94** [comment]
Currently it show 14 days left ? can you show the instruction step by step.

**Comment by sinanejadebrahim** [comment]
the license code i posted is old and doesn't have many days left, but if you use the repo I mentioned at the end, it will give you a license activated until 2089.

**Comment by sinanejadebrahim** [comment]
guys, you can use this new code, or you can generate it your self if you like.
```
AAAB+g0ODAoPeJyNU12PojAUfedXkOzjBmzRwY+kySriyIo6DrCT9a3iVTrD17bFGffXLwhmPjRmE15o7zn3nHNvv3lFqg5zrmKkImOA+wNkqoFvqQYyDGXPAdIoy3PgustCSAX4xxwWNAFiLedz+9Fyhq5icaCSZemYSiAVUEMdDSPlBmQMIuQsr1AkSGOWMAlbNa4B6uaoRlLmYtBq/Y1YDDrLlDllqYSUpiHYbznjx6Zbr6+hbvkpz4zTs0p7y2rqhevMHd8eK4si2QBf7gIBXBANn8Xd4Mp5ti1CqVc/msh28pVy0C+IbtTSULIDEMkL+JTlx/Mb8FIVtaB0zevSJp5fZePKnKF4xeY9xlOJfaBxcRoG2dFYNPRfiZZ8T1Mm6roq6TJo3G/ruIN1bJg6xr1BDyGsWFkqS7F2GX5MhJ7oz/RAt6y8+rFPyjM9zJK6xUUsjdgpFRGZW8iarKxJ27v/zhLjPnl9Sqcrx/Lcdb4wZv31ygmmeBYf//xOWiNv7XaXuwhPneDhpZV1Ealb/GdqnqS8clr7b8bsjInrjD17obnY7PTv7rq4Y5oIf9qaa4vqAT8AL+Gj0ZOtIfcn1oKlMdEc358pL3A8DwObCHVRr93G117N5T4+FDyMqICvb+Yj+DSxnDPRmC7lkysWmiGdlI+G/j+VCElqMCwCFGxrnjz1G0V5MDwiLbn3gPiP6BUqAhRxlZk+6MN8sZsehGcEYqlhbQxMyg==X02o0```

**Comment by sinanejadebrahim** [comment]
@ozcan-durak @dinhquy94 @
just wanted to let you know that i've updated the repo with a new code, you can use it if you want.
