### ISSUE TITLE
Confluence?

### ISSUE THREAD

**Issue by Pavel077** [sinanejadebrahim/jira-crack#4]
Hello!

Perhaps you have an edited version of "atlassian-extras-decoder-v2-3.4.6.jar" needed for confluence?

**Comment by sinanejadebrahim** [comment]
hi, sorry but no.
but I've heard from people that the same code works for all of the products.

**Comment by Pavel077** [comment]
Thank you.
I ended using https://github.com/IAlexEgorov/AtlassianCrack

**Comment by sinanejadebrahim** [comment]
you're welcome and thank you for sharing this repo,
other people might end up using it too.

**Comment by mariano-daniel** [comment]
> https://github.com/IAlexEgorov/AtlassianCrack

Hello, did you manage to get it working? Which Confluence version you used? I couldn't get it to work in the latest DC version, neither on `7.3.5`, whatever licence code I generate, Confluence tells me it's invalid.
