### ISSUE TITLE
9.6 version

### ISSUE THREAD

**Issue by timeshift92** [sinanejadebrahim/jira-crack#5]

**Comment by TechMorgan** [comment]
https://github.com/nineaiyu/atlassian-agent
https://blog.csdn.net/ly1358152944/article/details/126460617

**Comment by sinanejadebrahim** [comment]
@TechMorgan 
thank you for sharing

**Comment by mariano-daniel** [comment]
> https://github.com/nineaiyu/atlassian-agent
> https://blog.csdn.net/ly1358152944/article/details/126460617
> Also works on Windows
> It's recommended to do this in offline

I tried to get his compiled package but it's hosted in Baidu file sharing, which requires me to have a Baidu account (which I cannot get due to me not being in China, also I cannot create any VM from China to setup a VPN). Do you know how can  I get my hands on such compiled package?

**Comment by TechMorgan** [comment]
> > https://github.com/nineaiyu/atlassian-agent
> > https://blog.csdn.net/ly1358152944/article/details/126460617
> > Also works on Windows
> > It's recommended to do this in offline
> 
> I tried to get his compiled package but it's hosted in Baidu file sharing, which requires me to have a Baidu account (which I cannot get due to me not being in China, also I cannot create any VM from China to setup a VPN). Do you know how can I get my hands on such compiled package?


You can do it yourself easily.
1. Download jira and atlassian agent.
2. Create a database
3. Add the paths mentioned in both websites.
4. Make sure you are offline, go to the key cracking part, follow it and fill in the license key on the page.
5. Done.

**Comment by mariano-daniel** [comment]
> > > https://github.com/nineaiyu/atlassian-agent
> > > https://blog.csdn.net/ly1358152944/article/details/126460617
> > > Also works on Windows
> > > It's recommended to do this in offline
> > 
> > 
> > I tried to get his compiled package but it's hosted in Baidu file sharing, which requires me to have a Baidu account (which I cannot get due to me not being in China, also I cannot create any VM from China to setup a VPN). Do you know how can I get my hands on such compiled package?
> 
> For Linux, follow sinanejadebrahim's repo. If you are on Windows, you can do it yourself easily.
> 
> 1. Create a database in Postgres or mysql.
> 2. Download and install Jira.
> 3. During installation, create a path for Jira home directory and installation directory separately.
> 4. After installation, download atlassian agent from the repo and place it in Jira Home directory.
> 5. Configure the database and jira home directory path in jira config tool(config.bat file) which is inside "..\Jira Software\bin folder".
> 6. Add this in environment variables(change attassian agent jar file path): CATALINA_OPTS=-javaagent:path\to\jira-home\atlassian-agent.jar=%CATALINA_OPTS%
> 7. Make sure you are offline.
> 8. Start Jira from start-jira.bat in bin folder.
> 9. Follow the key cracking part in the blog and fill in the license key on the page.
> 10. Done.
> 
> Another tutorial for running it in docker, https://github.com/haxqer/jira

Hello @TechMorgan ! Thank you for your response. I'm on MacOS though.

I tried following sinanejadebrahim's instructions, but the code mentioned here:

![image](https://github.com/sinanejadebrahim/jira-crack/assets/60707523/9deaa693-1831-47bb-99a1-9a4842cc2b57)


Does not work, so I followed his next instructions as per:

![image](https://github.com/sinanejadebrahim/jira-crack/assets/60707523/655b6ead-d42f-490b-9c7e-ea87469209dd)

But that's when I run into https://gitee.com/pengzhile/atlassian-agent and need to download his script from Baidu and cannot access it.

**Comment by mariano-daniel** [comment]
> > But that's when I run into https://gitee.com/pengzhile/atlassian-agent and need to download his script from Baidu and cannot access it.
> 
> Use this link: https://github.com/nineaiyu/atlassian-agent

Hello again @TechMorgan ! That's the link i'm using.

I go to the option "f you don't know what I'm talking about, it's better to just download my compiled package." Because I have no idea how to properly use Maven and those sorts of tools.

But nowhere on the Git page you can find the self compiled package. That's when I visit the link stated at the bottom of the page, that takes you to [https://zhile.io/2018/12/20/atlassian-license-crack.html](url) but then I run into the ordeal of having to download it from a Chinese dropbox that does not support ip's outside China. 😢

**Comment by TechMorgan** [comment]
> you don't

No need of those maven, etc.. things. Download the jar file from releases in that repo and use it.

**Comment by mariano-daniel** [comment]
> > I go to the option "f you don't know what I'm talking about, it's better to just download my compiled package." Because I have no idea how to properly use Maven and those sorts of tools.
> > But nowhere on the Git page you can find the self compiled package. That's when I visit the link stated at the bottom of the page, that takes you to [https://zhile.io/2018/12/20/atlassian-license-crack.html](url) but then I run into the ordeal of having to download it from a Chinese dropbox that does not support ip's outside China. 😢
> 
> Hii, @mariano-daniel. You don't need those maven, etc.. things. Just download the jar file from [releases](https://github.com/nineaiyu/atlassian-agent/releases/latest) in that repo and use it.

Alright thank you! I've downloaded the `.jar`file and ran it as instructed (`java -jar atlassian-agent.jar`) now when I run `./start-jira.sh` I get the following error:

![image](https://github.com/sinanejadebrahim/jira-crack/assets/60707523/db2f42bd-fef2-46de-97d0-6079a906adb8)


Only significant Jira startup log entries are:

```
2023-06-07 05:15:27,354+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.JiraStartupLogger] Running Jira startup checks.
2023-06-07 05:15:27,354+0000 JIRA-Bootstrap FATAL      [c.a.jira.startup.JiraStartupLogger] Startup check failed. Jira will be locked.
2023-06-07 05:15:27,563+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.LauncherContextListener] Startup is complete. Jira is ready to serve.
2023-06-07 05:15:27,566+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.LauncherContextListener] Memory Usage:
```

What can I be doing wrong?

**Comment by TechMorgan** [comment]
> Alright thank you! I've downloaded the `.jar`file and ran it as instructed (`java -jar atlassian-agent.jar`) now when I run `./start-jira.sh` I get the following error:
> 
> ![image](https://user-images.githubusercontent.com/60707523/243919311-db2f42bd-fef2-46de-97d0-6079a906adb8.png)
> 
> Only significant Jira startup log entries are:
> 
> ```
> 2023-06-07 05:15:27,354+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.JiraStartupLogger] Running Jira startup checks.
> 2023-06-07 05:15:27,354+0000 JIRA-Bootstrap FATAL      [c.a.jira.startup.JiraStartupLogger] Startup check failed. Jira will be locked.
> 2023-06-07 05:15:27,563+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.LauncherContextListener] Startup is complete. Jira is ready to serve.
> 2023-06-07 05:15:27,566+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.LauncherContextListener] Memory Usage:
> ```
> 
> What can I be doing wrong?
> 
>
Check if your jira home directory is configured correctly. Use config.sh to set the jira home directory. And make sure the jira installation path and jira home path is different.
> **Edit:** Hmmm, maybe I need to figure out the different options?:
> 
> ```
> KeyGen usage: java -jar /home/dieter.hansx90/atlassian-agent.jar [-d] [-h] -m
>        <arg> [-n <arg>] -o <arg> -p <arg> -s <arg>
> ```

Use the full command from the the key cracking part in the blog. Your command contains only the half.

**Comment by mariano-daniel** [comment]
> Go offline and start jira. Follow the full command from the key cracking part in the blog cuz your command contains only the half part.

Can you point me exactly to this part? Thank you!

**Comment by mariano-daniel** [comment]
Now I think they've banned the licence key:

![image](https://github.com/sinanejadebrahim/jira-crack/assets/60707523/616ccce5-0842-49ba-804f-09c29a8ea360)

**Comment by TechMorgan** [comment]
> Now I think they've banned the licence key:
> 
> ![image](https://user-images.githubusercontent.com/60707523/244599133-616ccce5-0842-49ba-804f-09c29a8ea360.png)

That works when you are offline.
Ok, you can try this, I don't whether this works. Install jira in your local machine in offline, and copy the installed files and home directory to the vm.

**Comment by mariano-daniel** [comment]
> That works when you are offline. Ok, now follow the below, I don't know whether this works, but you can try. Install jira on your local machine like you have done it on the VM, run the cracking command `java -jar path/to/atlassian-agent.jar -m 'jira@qq.com' -p jira -o 'put_base_url' -s 'put_server_id'`, finish it and copy the installation directory and home directory to the vm. On vm, run config.sh to set the jira home path

Hello again @TechMorgan , I really appreciate all the help and effort you're putting into giving me a hand! Do you have a [Ko-fi account ](https://ko-fi.com)or PayPal where I can buy you a beer or coffee? 🍻

At the moment I got this error:

```
We're unable to confirm that Jira license
This license is invalid. Please double-check that you have entered it correctly, and contact Support if the issue continues.
```

Now, I managed to succeed with the steps [on the blog](https://github.com/sinanejadebrahim/jira-crack) for Jira Software (not using `atlassian-agent.jar`) ; but now I need to replicate the results on Jira Service Desk (my original goal), yet I can't , I use the switch `-p jsd` but the licence is no good.
When I download Jira SD and follow the steps on the blog, I always get thrown into a Jira Software product:

![image](https://github.com/sinanejadebrahim/jira-crack/assets/60707523/433c3caf-65ac-4012-b85f-34fcc9da6d6b)

Do you believe there is a way I can use the steps [on the blog](https://github.com/sinanejadebrahim/jira-crack) to activate Jira SD or is it only for Jira Software?

Thanks in advance!

**Comment by TechMorgan** [comment]
> Hello again @TechMorgan , I really appreciate all the help and effort you're putting into giving me a hand! Do you have a [Ko-fi account ](https://ko-fi.com)or PayPal where I can buy you a beer or coffee? 🍻
> 
It's okay, no problem 😊. I'm always interested in helping tech issues for anyone.

> At the moment I got this error:
> 
> ```
> We're unable to confirm that Jira license
> This license is invalid. Please double-check that you have entered it correctly, and contact Support if the issue continues.
> ```
> 
> Now, I managed to succeed with the steps [on the blog](https://github.com/sinanejadebrahim/jira-crack) for Jira Software (not using `atlassian-agent.jar`) ;

👍Nice work

> but now I need to replicate the results on Jira Service Desk (my original goal), yet I can't , I use the switch `-p jsd` but the licence is no good. When I download Jira SD and follow the steps on the blog, I always get thrown into a Jira Software product:
> 
> ![image](https://user-images.githubusercontent.com/60707523/244847103-433c3caf-65ac-4012-b85f-34fcc9da6d6b.png)
> 
> Do you believe there is a way I can use the steps [on the blog](https://github.com/sinanejadebrahim/jira-crack) to activate Jira SD or is it only for Jira Software?
> 
> Thanks in advance!
> 
> **Update:** I followed the steps on the blog for Jira SD and I'm still prompted to enter a licence.


Use the jar file and in the -p parameter use jsd instead of jira, so it comes as, `-p jsd`

**Comment by TechMorgan** [comment]
> Hello again @TechMorgan , I really appreciate all the help and effort you're putting into giving me a hand! Do you have a [Ko-fi account ](https://ko-fi.com)or PayPal where I can buy you a beer or coffee? 🍻
> 
It's okay, no problem 😊. I'm always interested in helping tech issues for anyone.


> Now, I managed to succeed with the steps [on the blog](https://github.com/sinanejadebrahim/jira-crack) for Jira Software (not using `atlassian-agent.jar`) ; 

👍Nice work

> but now I need to replicate the results on Jira Service Desk (my original goal), yet I can't , I use the switch `-p jsd` but the licence is no good. When I download Jira SD and follow the steps on the blog, I always get thrown into a Jira Software product:
> 
> ![image](https://user-images.githubusercontent.com/60707523/244847103-433c3caf-65ac-4012-b85f-34fcc9da6d6b.png)
> 
> Do you believe there is a way I can use the steps [on the blog](https://github.com/sinanejadebrahim/jira-crack) to activate Jira SD or is it only for Jira Software?
> 

The jsd parameter is the only way to get the license for SD

**Comment by mariano-daniel** [comment]
> Following [jira-crack](https://github.com/sinanejadebrahim/jira-crack) repo is for Jira software. After installing it, if you have installed service desk, go to jira > applications > jira service desk > paste the license > paste the key you got from atlassian-agent. I just used the command from the [blog](https://blog.csdn.net/ly1358152944/article/details/126460617) and used `jsd` instead of `jira`. It worked for me..

![image](https://github.com/sinanejadebrahim/jira-crack/assets/60707523/41b2db60-b5ba-4d54-8609-0fe0dd26a16c)


Thank you!! That worked flawlessly! I was missing that part! I am really really thankful for all the help and patience you showed. This will help me practise and learning to use this tool much more than at work. Thanks again I super appreciate it!

**Comment by TechMorgan** [comment]
> Thank you!! That worked flawlessly! I was missing that part! I am really really thankful for all the help and patience you showed. This will help me practise and learning to use this tool much more than at work. Thanks again I super appreciate it!

 You're welcome 😊. I'm glad to hear that it worked.  If you ever have any more questions or need further assistance, feel free to reach out.

Telegram: t.me/deepsmorgan

**Comment by ithelpdeskBMBS** [comment]
Update, Work For me Jira 9.11.2 ,,, 
![image](https://github.com/guywiththecrack/jira-crack/assets/134051843/269ebb22-e59c-4fa0-a781-633341dbd771)

**Comment by guywiththecrack** [comment]
@mariano-daniel @timeshift92 @TechMorgan @ithelpdeskBMBS 
just a quick update for you all - ive updated the repo and it just works easily with latest version - check it out 
thank you for helping others
